/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketplaceSol from "./Marketplace.sol";
export type { marketplaceSol };
import type * as retirementAgentSol from "./RetirementAgent.sol";
export type { retirementAgentSol };
export type { CarbonCredit } from "./CarbonCredit";
export type { MockUSDT } from "./MockUSDT";
