/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICarbonCredit,
  ICarbonCreditInterface,
} from "../../../contracts/Marketplace.sol/ICarbonCredit";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "projectId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "marketplaceTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICarbonCredit__factory {
  static readonly abi = _abi;
  static createInterface(): ICarbonCreditInterface {
    return new Interface(_abi) as ICarbonCreditInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICarbonCredit {
    return new Contract(address, _abi, runner) as unknown as ICarbonCredit;
  }
}
