/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICarbonCredit__factory } from "./ICarbonCredit__factory";
export { Marketplace__factory } from "./Marketplace__factory";
