/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICarbonCreditRetirement,
  ICarbonCreditRetirementInterface,
} from "../../../contracts/RetirementAgent.sol/ICarbonCreditRetirement";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "projectId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "retireFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICarbonCreditRetirement__factory {
  static readonly abi = _abi;
  static createInterface(): ICarbonCreditRetirementInterface {
    return new Interface(_abi) as ICarbonCreditRetirementInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICarbonCreditRetirement {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICarbonCreditRetirement;
  }
}
