/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICarbonCreditRetirement } from "./ICarbonCreditRetirement";
export type { RetirementAgent } from "./RetirementAgent";
